"""Realize registration User

Revision ID: 9b68ba163cba
Revises: 237716716c8f
Create Date: 2026-07-26 05:14:15.066367

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '9b68ba163cba'
down_revision: str | Sequence[str] | None = '237716716c8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
